branches:
  only:
    - master
    - dev
os:
  - linux
language: node_js
node_js:
  - 12
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:unit -- --coverage --coverageReporters=lcov
  - npm run test:e2e
after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls

before_deploy:
  - npm run build
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export PACKAGE=$(npm pack --silent)
  - git tag $PACKAGE_VERSION
deploy:
  - provider: releases
    skip_cleanup: true
    file: $PACKAGE
    api_key:
      secure: Z4+zHdz07/2oO6QPIeSk/ZaS8+QwldjYPc0iRPIF/6N0Cww35EIMvtEm/tLMyZcw8kYJHAdh9v7q/bNrBwCdhmZ7/8d4qk8cFfqhxjWfA/8EnA8Juo+5+3gkUpYPukcNtDlaei3l++96k3sQ4FyYxuEpY3lWGzFwJggWA+LQGVebGKDreFnVytEr8DeXnOUhCamN39uv8xqrbJufvp+3vWNXu4PwRd5R7N+HqoZGPIQMa8rJwbPhW2cJF4bQoy7ZNzhh6/C0UbhEG9ykBWy/9VXIjxq46RJcWXVSq0dUEhhGWn34F5OZqDxOElPDzntXpunbNb1HnDFCw/hWy4BhDTlNI7DLhFc1R4+PRfd0c0lY1flHt/Xza5O4kV7P24bhZHuf8qVQyWjBg6mf+AOON88k7ewPyqKbkYphoeGdG0AktMcJ3CMbsKvgYtp/+K0mVtPsrgrFkJrXK9vgUazhBlkeq8PRxOrkTP9XeazZR6WzE7tJAmd612Q8Ij7zC1KNyXD1OCoFUs5KkjVD0vx7dM5jafWjhd3GWTegGJgQ/OOecXbfsigvwbSeaMN9Mh9RP8XrKXV8ajj7QeqhHOCzBtt4OukhjXXoU24BK3/Lak/WznKbrnVdtEORlU0jPcnXJvKrMrsRjeHQOeqZOTs4Mgt2GXcKGnzvTbsZVyceMZI=
    on:
      repo: eidng8/vue-tree
      branch: master
      #tags: true
